version: '3.9'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: moderator_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "3100:5432"

volumes:
  pgdata: